### ISSUE TITLE
prefer rad over deg

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/Steca#35]

**Comment by ghost** [comment]
We've had a long talk about it in the beginning of Steca2 development; we have carefully considered both options: keeping data internally either as deg or as rad. Since input/output is in deg and trigonometric functions need rad, there will always be conversion somewhere. It turned out that keeping data internally as deg means fewer conversions and simpler code.

**Comment by jwuttke** [comment]
The conversions, though, take place in an innermost loop. Can we measure whether this has noticeable impact upon performance?

**Comment by jwuttke** [comment]
The possible marginal gain in speed will not justify the effort & risk of such complex refactoring. Stay with deg.
